### PR TITLE
JSON tidy, and fix #7 (reverted - broken PR)

### LINKED ISSUE #7: PSA: macOS 15.1 opens "Apple Intelligence" instead of Spotlight if that feature is enabled
This isn't a problem with the workflow, just an observation.

I noticed that when Apple Intelligence is enabled on macOS 15.1 (beta), the URI:

```
x-apple.systempreferences:com.apple.preference.spotlight
```

...opens **Apple Intelligence & Siri** instead. That's annoying. 

I wonder if there's a new URI to get to one or the other explicitly. ~~I haven't found it yet.~~

### PR DESCRIPTION
**Pull request by luckman212**
related issue: https://github.com/Stephen-Lon/Alfred-workflow-open-macos-settings-panes/issues/7

This PR just makes a few minor changes

- tidies up the JSON in the `syset.sh` script (tabs → spaces, remove some dangling `,`)
- adds a shebang so the script can be called directly as an External Script
- adds explicit URI for Spotlight so that does the right thing on macOS 15.1

screenshot_qbonCRmi

### CODE REVIEW

**Comment by luckman212** [comment]
Oops. Did not mean to include README in my PR. I'll fix that.

**Comment by luckman212** [comment]
@Stephen-Lon Please roll that commit back, the dummy README was included by accident. I am fixing now.

**Comment by Stephen-Lon** [comment]
Sorry I am completely lost in the maze of GitHub. Am not an expert and have little idea of what I'm doing. No idea how to roll back the commit and no idea what I have to do to create new release incorporating what is finally merged. Sorry to be so ignorant.

**Comment by luckman212** [comment]
@Stephen-Lon Since you already merged this, I don't have the ability to close it. 

I reverted the commits to the README and submitted a totally new PR here: https://github.com/Stephen-Lon/Alfred-workflow-open-macos-settings-panes/pull/9

If you need help reverting the merge, check out this page, it should be fairly simple:

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/reverting-a-pull-request

Once you've rolled that back, you should be able to merge #9 without complication.

I also note: `syset.sh` isn't even contained in your git repo for some reason, I had to pull it in from my .alfredworkflow in order to submit the change. I assume that's an oversight?

**Comment by luckman212** [comment]
Looks like you successfully did it. Thanks and sorry for all the fuss on a Sunday.

**Comment by Stephen-Lon** [comment]
No problem at all. I much appreciate both your contribution and, particularly, your patience with a GitHub novice. Once again, sorry for my ignorance!

**Pull request merged**
